name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Modifica el Vite Config para GitHub Pages
      - name: Update Vite Config for GitHub Pages
        run: |
          sed -i "s/plugins: \[react(), tailwindcss(), VitePWA/base: '\/${{ github.event.repository.name }}\/',\n    plugins: \[react(), tailwindcss(), VitePWA/" vite.config.ts
          
      # Instalación limpia para evitar el error de npm/Tailwind
      - name: Clean Install
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install @rollup/rollup-linux-x64-gnu --no-save
          
      - name: Build Application
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
